
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: internal_tools
      MYSQL_USER: dev
      MYSQL_PASSWORD: s3glm4eBfHd7e8
      ports:
      - "3315:3306"
    volumes:
      -  mysql_data:/var/lib/mysql

      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###